name: "debug"
tag: "${rmspace:${data.dataset},_}" 
exp_root_dir: "outputs"
seed: 0

data_type: "medmnist2d-datamodule"
data:
  dataset: breastmnist
  dataroot: /data2/medmnist/
  download: true
  as_rgb: true

  size: 28
  resize: 224

  train_batch_size: 64 # 4
  val_batch_size: 64 # 4
  test_batch_size: 64 # 4

  train_workers: 8
  val_workers: 8
  test_workers: 8

trainer_type: "-"
trainer:
  model_type: "topo-cnn"
  model:
    betti_upsample_to: 64

    network_type: network-resnet
    network:
      model: resnet18
      pretrained: false

      in_ch: 3
      out_ch: 256

    classifier_type: classifier-linear
    classifier:
      in_ch: ${trainer.model.network.out_ch}

      ch: 128

      out_dim: 1

      aux_ch_in: 0

      dropout_in: 0.2
      dropout_feat: 0.2

  loss:
    lambda_bce: 1.0 
    lambda_focal: 0.0 
    lambda_minimal_filt: 0.0
    lambda_maximal_filt: 0.0
  
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      weight_decay: 0.01

  scheduler:
    name: CosineWarmup
    interval: step
    args:
      warmup_epochs: 10
      min_lr: 5e-4
  visualize: false

pl_trainer:
  max_epochs: 100
  log_every_n_steps: 4
  enable_progress_bar: true
  precision: 32
  benchmark: true # cudnn_benchmark
  # detect_anomaly: true

checkpoint:
  save_last: true
  save_top_k: 5
  monitor: "val/roc_auc"
  mode: "max"
  filename: "epoch={epoch}-val_roc_auc={val/roc_auc}-val_accuracy={val/accuracy}"
  auto_insert_metric_name: false

test_final: True
test_best_val: true