name: "v3d-r18-acs-concat"
tag: "${rmspace:${data.dataset},_}-${data.size}" 
exp_root_dir: "outputs3d"
seed: 0

data_type: "medmnist3d-datamodule"
data:
  dataset: adrenalmnist3d
  dataroot: /data2/medmnist/
  download: true
  as_rgb: true

  size: 64 
  # size: 28
  # resize: 224

  train_batch_size: 16
  val_batch_size: 16
  test_batch_size: 16

  train_workers: 16
  val_workers: 16
  test_workers: 16

  has_betti_data: True
  betti_data_csv: "/data2/ck223/medmnist/size224/{split}_{size}_{name}_BettiVectors_100.csv"

trainer_type: "classification-trainer"
trainer:
  betti_aux: true

  model_type: "concat-classifier"
  model:
    network_type: network-resnet3d
    network:
      model: resnet18
      conv: ACSConv
      pretrained_3d: i3d

      in_ch: 3
      out_ch: 128

    aux_network_type: network-mlp
    aux_network:
      in_ch: 300
      hidden:
        - 256
        - 256
      out_ch: 128

    classifier_type: classifier-linear
    classifier:
      in_ch: ${add:${trainer.model.network.out_ch},${trainer.model.aux_network.out_ch}}
      ch: 256
      out_ch: 1

      dropout_in: 0.0
      dropout_feat: 0.0

  task: binary
  loss:
    lambda_ce: 1.0
  
  optimizer:
    name: Adam # AdamW
    args:
      lr: 0.001 # 0.01
      # weight_decay: 0.01

  # scheduler:
  #   name: CosineWarmup
  #   interval: step
  #   args:
  #     warmup_epochs: 10
  #     min_lr: 5e-4

  scheduler:
    name: MultiStepLR
    interval: epoch
    args:
      gamma: 0.1
      milestones:
        - ${mul:0.5,${pl_trainer.max_epochs}}
        - ${mul:0.75,${pl_trainer.max_epochs}}

pl_trainer:
  max_epochs: 100
  log_every_n_steps: 1
  enable_progress_bar: true
  precision: 32
  benchmark: true # cudnn_benchmark
  # detect_anomaly: true

checkpoint:
  save_last: true
  save_top_k: 3
  monitor: "val/roc_auc"
  mode: "max"
  filename: "epoch={epoch}-val_roc_auc={val/roc_auc}-val_accuracy={val/accuracy}"
  auto_insert_metric_name: false

test_final: true
test_best_val: true